version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jsonplaceholder
      POSTGRES_USER: jsonuser
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: jsonplaceholder
      DB_USER: jsonuser
      DB_PASSWORD: changeme
      JWT_SECRET: devSecretKey1234567890devSecretKey123456
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata: 